#!/usr/bin/with-contenv /bin/bash
echo 'Starting snapserver'
echo '[stream]' > /snapserver.conf
for var in ${!stream*}
do
  echo "source = ${!var}" >> /snapserver.conf
done
echo "Configuration:"
cat /snapserver.conf
exec snapserver -c /snapserver.conf
#exec snapserver -s pipe:///pipes/noise?name=Noise -s pipe:///pipes/music?name=Music

