#!/usr/bin/with-contenv /bin/bash
echo 'Starting snapserver'
echo '[stream]' > /snapserver.conf
for var in ${!stream*}
do
  echo "source = ${!var}" >> /snapserver.conf
done
echo "Configuration:"
cat /etc/snapserver.conf
